feat: Add level field to spells generally and by class (and whatever has a "level" field that gets prewarmed into Redis)
5e-bits/5e-srd-api pull request #411
Opened 2024-02-23 18:36 UTC by BenTracyDotCom

## What does this do?
Adds level field to returned general and class (short) spell data

## How was it tested?
```npm test``` & practical test on local machine

## Is there a Github issue this is resolving?
No

## Was any impacted documentation updated to reflect this change?
N/A

## Here's a fun image for your troubles
![random photo - update me](https://picsum.photos/200)

2024-04-03 17:40 UTC, bagelbits approved these changes

2024-04-03 17:41 UTC, bagelbits requested changes
Can you please update https://github.com/5e-bits/docs as well? The docs should reflect this change.

2024-04-04 19:00 UTC, BenTracyDotCom commented
> Can you please update https://github.com/5e-bits/docs as well? The docs should reflect this change.

Updated docs and PR'd

2024-04-04 22:53 UTC, bagelbits approved these changes
This looks good and I made sure all tests pass. However, this is blocked by some changes you need to make on the Docs PR.

2024-04-09 22:41 UTC, bagelbits commented
Related Docs PR:
https://github.com/5e-bits/docs/pull/33

2024-04-10 15:22 UTC, merged